name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build && PUSH the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" |docker login -u "nelab" --password-stdin
        docker build . --file Dockerfile --tag nelab/hcm-frontend:latest
        docker push nelab/hcm-frontend:latest
